### ISSUE TITLE
I have a question about option value

### ISSUE THREAD

**Issue by dtrxx14** [buonzz/jquery-ph-locations#19]
How can I change the value of it's option to name?

build_options(params){
				var shtml = "";

				for(var i=0; i<params.data.length;i++){
					shtml += '<option value="' + params.data[i].id + '">';
					shtml +=  params.data[i].name ;
					shtml += '</option>';
				}

				return shtml
			}

this code

I am changing the params data to name but when I am changing it. it did not display the other data in select type.

**Comment by Makcintoshawesome** [comment]
> How can I change the value of it's option to name?
> 
> build_options(params){
> var shtml = "";
> 
> ```
> 			for(var i=0; i<params.data.length;i++){
> 				shtml += '<option value="' + params.data[i].id + '">';
> 				shtml +=  params.data[i].name ;
> 				shtml += '</option>';
> 			}
> 
> 			return shtml
> 		}
> ```
> 
> this code
> 
> I am changing the params data to name but when I am changing it. it did not display the other data in select type.

same question

**Comment by migsyyy** [comment]
I'm thinking you have to run a script afterwards, since I don't see any options in the documentation.

**Comment by buonzz** [comment]
Hi @dtrxx14,

the API only receives the  numeric code when filtering. That is why the other data in select type is not showing. If you want to retrieve the name of the location, you can simple get the caption of the selected option and save that in a hidden field, for example

HTML
```
<form>
<input type="hidden" name="region"/>
<select id="region-selector"></select>
</form>
```

JavaScript
```
$(function(){

// whenever the region dropdown change, update the value of hidden field
 $('#region-selector').on('change', function(){

       // we are getting the text() here, not val()
       var selected_caption = $("#region-selector option:selected").text();

      // the hidden field will contain the name of the region, not the code
       $('input[name=region]').val(selected_caption);

 }).ph_locations('fetch_list');

});

```

In your backend, you will receive the name of the province (not the code ).
