### ISSUE TITLE
Alphabetically sort items upon fetching?

### ISSUE THREAD

**Issue by migsyyy** [buonzz/jquery-ph-locations#23]
Is there an option to have the options sorted alphabetically once fetch_list is called? thanks

**Comment by buonzz** [comment]
Hi @migsyyy,

this is now fixed.

1. by default, it will automatically sort the dropdown items alphabetically
2. If you need more control of the sorting, you can pass a `order` parameter to the plugin

```
$('#region').ph_locations({
    "location_type": "regions",
    "order" : "name asc"
});
```

the value of the order parameter is <field> <sort direction>

* possible values for field: name, region_code
* possible values for sort direction: asc, desc

let me know if that works for you :)

**Comment by migsyyy** [comment]
> Hi @migsyyy,
> 
> this is now fixed.
> 
> 1. by default, it will automatically sort the dropdown items alphabetically
> 2. If you need more control of the sorting, you can pass a `order` parameter to the plugin
> 
> ```
> $('#region').ph_locations({
>     "location_type": "regions",
>     "order" : "name asc"
> });
> ```
> 
> the value of the order parameter is
> 
> * possible values for field: name, region_code
> * possible values for sort direction: asc, desc
> 
> let me know if that works for you :)

Thanks a lot! It works now. This is a big help. And btw PSA just recently released updates on some barangay names. Again, thanks a lot!
