### ISSUE TITLE
Getting text value of each region, city , province and barangay

### ISSUE THREAD

**Issue by rivg26** [buonzz/jquery-ph-locations#27]
Hello paano po kuhain yung mismong value I mean yung text value instead of numbers na value na galing sa PSA? Thank you!

**Comment by TheBUGSS** [comment]
> Hello paano po kuhain yung mismong value I mean yung text value instead of numbers na value na galing sa PSA? Thank you!
lods nagawa mo na ba yung makuha text value ?pa help lods

**Comment by buonzz** [comment]
na check nyo na bro ung thread sa #19 ?
