### ISSUE TITLE
Select tag

### ISSUE THREAD

**Issue by TheBUGSS** [buonzz/jquery-ph-locations#28]
Bro how can i put optgroup in select tag .
thank you bro

**Comment by buonzz** [comment]
it doesnt have support for opt group yet. but can you give an example situation where this is needed?

**Comment by TheBUGSS** [comment]
boss paano yung location na yung first option kahit hindi na pindotin may magiging value ?
example
region (ARRM)
province (ARBA)

pwede bang magiging yan na yung value kahit hindi pa ako nag select?

advance thank you

**Comment by buonzz** [comment]
> boss paano yung location na yung first option kahit hindi na pindotin may magiging value ? example region (ARRM) province (ARBA)
> 
> pwede bang magiging yan na yung value kahit hindi pa ako nag select?
> 
> advance thank you

there is a new feature incoming to support providing default value. https://github.com/buonzz/jquery-ph-locations/commit/2a30ee005bfdef32df17b412b70855d7ae239e34
