### ISSUE TITLE
Auto populate region and province

### ISSUE THREAD

**Issue by neiljondc** [buonzz/jquery-ph-locations#30]
Is there a way to auto populate region and province? 
In City, I want to start with the pre-select Province which is Pampanga.

but when I add the code

`var my_handlers = {

				fill_provinces:  function(){

					 var region_code = $(this).val();
					 $('#province-selector').ph_locations('fetch_list', [{"region_code": "03"}]);
					 
				},

				fill_cities: function(){

					 var province_code = $(this).val();
					 $('#city-selector').ph_locations( 'fetch_list', [{"province_code": "0354"}]);
				},

				fill_barangays: function(){

					 var city_code = $(this).val();
					 $('#barangay-selector').ph_locations('fetch_list', [{"city_code": "035401"}]);
				}
		  };`

it's not populating the record, its still showing all records

**Comment by kooyaniks** [comment]
Same concern, di na pi-filter ung specific area if ilalagay ung mismong code.

Sir @buonzz , the concern is, we are trying to display the name of the area by putting the code as you mentioned in the Usage #4
