### ISSUE TITLE
Initialize Values

### ISSUE THREAD

**Issue by bendomachine** [buonzz/jquery-ph-locations#31]
Hey bro, Is it possible to put “- Select Region -“ followed by the Region name? I am encountering a little problem like in Region, its automatically selects “ARMM” but when I click it, Provinces under “ARMM” won’t populate unless you select the next one and reselect again the “ARMM”.

Thanks in advance.

**Comment by buonzz** [comment]
hi @bendomachine  yeah i think its possible to do this. 
Just need to add a line of code in https://github.com/buonzz/jquery-ph-locations/blob/master/jquery.ph-locations.js#L68-L71

so that the 

```
var shtml = "";
```

should be : 
```
var shtml = '<option value="" disabled="disabled>'+ '- Select Region -' + '</option>';
```

i dont have the time to test it atm, but will be glad to accept a pull request.

**Comment by Darwinsuuu** [comment]
Thanks bro!! <3

**Comment by TheBUGSS** [comment]
@Darwinsuuu did you fix the problem? I have a problem like that too can you help me?

**Comment by bendomachine** [comment]
Yes, how can I help you?


Sent from Yahoo Mail for iPhone


On Thursday, March 24, 2022, 6:11 PM, TheBUGSS ***@***.***> wrote:




@Darwinsuuu did you fix the problem? I have a problem like that too can you help me?

**Comment by bendomachine** [comment]
@buonzz Thanks for the help. I really appreciate it.

I just added a few lines under "fetch_list: function (filter) {".

if (this.settings.location_type == "regions") {
filterfieldname="- SELECT REGION -";
} 
else if (this.settings.location_type == "provinces") {
filterfieldname="- SELECT PROVINCE -";
} 
else if (this.settings.location_type == "cities") {
filterfieldname="- SELECT CITY/MUNICIPALITY -";
				}
else {
filterfieldname="- SELECT BARANGAY -";
};

and I also added under "build_options"
shtml += '<option value="">'+ filterfieldname + '</option>';

**Comment by TheBUGSS** [comment]
thanks all by the way thanks too @bendomachine  its running now ^^

**Comment by karldaren** [comment]
> 

sir where can i put this code  shtml += ''+ filterfieldname + '';? i tried to put it under build options but nothing show

**Comment by bendomachine** [comment]
> > 
> 
> sir where can i put this code shtml += ''+ filterfieldname + '';? i tried to put it under build options but nothing show


**jquery.ph-locations.js**

/*
 *  jquery-ph-locations - v1.0.1
 *  jQuery Plugin for displaying dropdown list of Philippines' Region, Province, City and Barangay in your webpage.
 *  https://github.com/buonzz/jquery-ph-locations
 *
 *  Made by Buonzz Systems
 *  Under MIT License
 */
;( function( $, window, document, undefined ) {
	var filterfieldname = "";
	
	"use strict";

		// defaults
		var pluginName = "ph_locations",
			defaults = {
                location_type : "city", // what data this control supposed to display? regions, provinces, cities or barangays?,
				api_base_url: 'https://ph-locations-api.buonzz.com/',
				order: "name asc",
				filter: {}
            };

		// plugin constructor
		function Plugin ( element, options ) {
			this.element = element;
			this.settings = $.extend( {}, defaults, options );
			this._defaults = defaults;
			this._name = pluginName;
			this.init();
		}

		// Avoid Plugin.prototype conflicts
		$.extend( Plugin.prototype, {
			init: function() {
				return this
            },
            
			fetch_list: function (filter) {
				
				this.settings.filter = filter;
					
				$.ajax({
                    type: "GET",
                    url: this.settings.api_base_url + 'v1/' +  this.settings.location_type,
					success: this.onDataArrived.bind(this),
					data: $.param(this.map_parameters())
                });
				

				if (this.settings.location_type == "regions") {
					filterfieldname="- SELECT REGION -";
				} 
				else if (this.settings.location_type == "provinces") {
					filterfieldname="- SELECT PROVINCE -";
				} 
				else if (this.settings.location_type == "cities") {
					filterfieldname="- SELECT CITY/MUNICIPALITY -";
				}
				else {
					filterfieldname="- SELECT BARANGAY -";
				};
				

            }, // fetch list
            onDataArrived(data){
				var shtml = "";
				$(this.element).html(this.build_options(data));
			},

			map_parameters(){

				var mapped_parameter = {"filter": {
					"where": {},
					"order" : this.settings.order
					}
				};

				 for(var property in this.settings.filter)
				    mapped_parameter.filter.where[property] = this.settings.filter[property];

				 return mapped_parameter;
			},

			build_options(params){
				var shtml = "";
				shtml += '<option value="">'+ filterfieldname + '</option>';
				for(var i=0; i<params.data.length;i++){
					shtml += '<option value="' + params.data[i].id + '">';
					shtml +=  params.data[i].name ;
					shtml += '</option>';
				}

				return shtml
			}
            
		} );


		$.fn[ pluginName ] = function( options, args ) {
			return this.each( function() {
				var $plugin = $.data( this, "plugin_" + pluginName );
				if (!$plugin) {
					var pluginOptions = (typeof options === 'object') ? options : {};
					$plugin = $.data( this, "plugin_" + pluginName, new Plugin( this, pluginOptions ) );
				}
				
				if (typeof options === 'string') {
					if (typeof $plugin[options] === 'function') {
						if (typeof args !== 'object') args = [args];
						$plugin[options].apply($plugin, args);
					}
				}
			} );
		};

} )( jQuery, window, document );



**index.php**

<!DOCTYPE html>

<html lang="en">
	<head>
		
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	
		
	</head>
	
	<title>Philippine Address</title>
	
	<body>
		<div class="container-fluid" style="margin-top: 10px;">
			<div class="col col-4">
			<label for = "reg"><b>Region</b></label>
			<select class="form-control form-control-sm" id="region" name="region">
			</select>	
							
			<label for = "prov"><b>Province</b></label>
			<select class="form-control form-control-sm" id="province" name="province">
			</select>	

			<label for = "mun"><b>City/Municipality</b></label>
			<select class="form-control form-control-sm" id="city" name="city">
			</select>		

			<label for = "brgy"><b>Barangay</b></label>
			<select class="form-control form-control-sm" id="barangay" name="barangay">
			</select>
			</div>
		</div>
		
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		
		<script src="jquery.ph-locations.js"></script>
        <script type="text/javascript">
			$(document).ready(function(){
				var my_handlers = {
					fill_provinces:  function(){
						var region_code = $(this).val();	
						$('#province').ph_locations('fetch_list', [{"region_code": region_code}]);
					},
					fill_cities: function(){
						var province_code = $(this).val();
						$('#city').ph_locations( 'fetch_list', [{"province_code": province_code}]);
					},
					fill_barangays: function(){
						var city_code = $(this).val();
						$('#barangay').ph_locations('fetch_list', [{"city_code": city_code}]);
					}
				};
				$('#region').ph_locations({'location_type': 'regions'});
				$('#province').ph_locations({'location_type': 'provinces'});
				$('#city').ph_locations({'location_type': 'cities'});
				$('#barangay').ph_locations({'location_type': 'barangays'});
				$('#region').ph_locations('fetch_list');
				$('#region').change(my_handlers.fill_provinces);
				$('#province').change(my_handlers.fill_cities);
				$('#city').change(my_handlers.fill_barangays); 

			});
		</script>
		
	</body>
</html>

**Comment by karldaren** [comment]
> > > 
> > 
> > 
> > sir where can i put this code shtml += ''+ filterfieldname + '';? i tried to put it under build options but nothing show
> 
> **jquery.ph-locations.js**
> 
> /*
> 
> * jquery-ph-locations - v1.0.1
> * jQuery Plugin for displaying dropdown list of Philippines' Region, Province, City and Barangay in your webpage.
> * https://github.com/buonzz/jquery-ph-locations
> * Made by Buonzz Systems
> * Under MIT License
>   */
> 
> ```
> ;( function( $, window, document, undefined ) {
> 	var filterfieldname = "";
> 	
> 	"use strict";
> 
> 		// defaults
> 		var pluginName = "ph_locations",
> 			defaults = {
>                 location_type : "city", // what data this control supposed to display? regions, provinces, cities or barangays?,
> 				api_base_url: 'https://ph-locations-api.buonzz.com/',
> 				order: "name asc",
> 				filter: {}
>             };
> 
> 		// plugin constructor
> 		function Plugin ( element, options ) {
> 			this.element = element;
> 			this.settings = $.extend( {}, defaults, options );
> 			this._defaults = defaults;
> 			this._name = pluginName;
> 			this.init();
> 		}
> 
> 		// Avoid Plugin.prototype conflicts
> 		$.extend( Plugin.prototype, {
> 			init: function() {
> 				return this
>             },
>             
> 			fetch_list: function (filter) {
> 				
> 				this.settings.filter = filter;
> 					
> 				$.ajax({
>                     type: "GET",
>                     url: this.settings.api_base_url + 'v1/' +  this.settings.location_type,
> 					success: this.onDataArrived.bind(this),
> 					data: $.param(this.map_parameters())
>                 });
> 				
> 
> 				if (this.settings.location_type == "regions") {
> 					filterfieldname="- SELECT REGION -";
> 				} 
> 				else if (this.settings.location_type == "provinces") {
> 					filterfieldname="- SELECT PROVINCE -";
> 				} 
> 				else if (this.settings.location_type == "cities") {
> 					filterfieldname="- SELECT CITY/MUNICIPALITY -";
> 				}
> 				else {
> 					filterfieldname="- SELECT BARANGAY -";
> 				};
> 				
> 
>             }, // fetch list
>             onDataArrived(data){
> 				var shtml = "";
> 				$(this.element).html(this.build_options(data));
> 			},
> 
> 			map_parameters(){
> 
> 				var mapped_parameter = {"filter": {
> 					"where": {},
> 					"order" : this.settings.order
> 					}
> 				};
> 
> 				 for(var property in this.settings.filter)
> 				    mapped_parameter.filter.where[property] = this.settings.filter[property];
> 
> 				 return mapped_parameter;
> 			},
> 
> 			build_options(params){
> 				var shtml = "";
> 				shtml += '<option value="">'+ filterfieldname + '</option>';
> 				for(var i=0; i<params.data.length;i++){
> 					shtml += '<option value="' + params.data[i].id + '">';
> 					shtml +=  params.data[i].name ;
> 					shtml += '</option>';
> 				}
> 
> 				return shtml
> 			}
>             
> 		} );
> 
> 
> 		$.fn[ pluginName ] = function( options, args ) {
> 			return this.each( function() {
> 				var $plugin = $.data( this, "plugin_" + pluginName );
> 				if (!$plugin) {
> 					var pluginOptions = (typeof options === 'object') ? options : {};
> 					$plugin = $.data( this, "plugin_" + pluginName, new Plugin( this, pluginOptions ) );
> 				}
> 				
> 				if (typeof options === 'string') {
> 					if (typeof $plugin[options] === 'function') {
> 						if (typeof args !== 'object') args = [args];
> 						$plugin[options].apply($plugin, args);
> 					}
> 				}
> 			} );
> 		};
> 
> } )( jQuery, window, document );
> 
> 
> 
> **index.php**
> 
> <!DOCTYPE html>
> 
> <html lang="en">
> 	<head>
> 		
> 		<meta charset="utf-8">
> 		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
> 		
> 		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
> 	
> 		
> 	</head>
> 	
> 	<title>Philippine Address</title>
> 	
> 	<body>
> 		<div class="container-fluid" style="margin-top: 10px;">
> 			<div class="col col-4">
> 			<label for = "reg"><b>Region</b></label>
> 			<select class="form-control form-control-sm" id="region" name="region">
> 			</select>	
> 							
> 			<label for = "prov"><b>Province</b></label>
> 			<select class="form-control form-control-sm" id="province" name="province">
> 			</select>	
> 
> 			<label for = "mun"><b>City/Municipality</b></label>
> 			<select class="form-control form-control-sm" id="city" name="city">
> 			</select>		
> 
> 			<label for = "brgy"><b>Barangay</b></label>
> 			<select class="form-control form-control-sm" id="barangay" name="barangay">
> 			</select>
> 			</div>
> 		</div>
> 		
> 		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.js"></script>
> 		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.js"></script>
> 		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
> 		
> 		<script src="jquery.ph-locations.js"></script>
>         <script type="text/javascript">
> 			$(document).ready(function(){
> 				var my_handlers = {
> 					fill_provinces:  function(){
> 						var region_code = $(this).val();	
> 						$('#province').ph_locations('fetch_list', [{"region_code": region_code}]);
> 					},
> 					fill_cities: function(){
> 						var province_code = $(this).val();
> 						$('#city').ph_locations( 'fetch_list', [{"province_code": province_code}]);
> 					},
> 					fill_barangays: function(){
> 						var city_code = $(this).val();
> 						$('#barangay').ph_locations('fetch_list', [{"city_code": city_code}]);
> 					}
> 				};
> 				$('#region').ph_locations({'location_type': 'regions'});
> 				$('#province').ph_locations({'location_type': 'provinces'});
> 				$('#city').ph_locations({'location_type': 'cities'});
> 				$('#barangay').ph_locations({'location_type': 'barangays'});
> 				$('#region').ph_locations('fetch_list');
> 				$('#region').change(my_handlers.fill_provinces);
> 				$('#province').change(my_handlers.fill_cities);
> 				$('#city').change(my_handlers.fill_barangays); 
> 
> 			});
> 		</script>
> 		
> 	</body>
> </html>
> ```

tnx bro

**Comment by karldaren** [comment]
> > > 
> > 
> > 
> > sir where can i put this code shtml += ''+ filterfieldname + '';? i tried to put it under build options but nothing show
> 
> **jquery.ph-locations.js**
> 
> /*
> 
> * jquery-ph-locations - v1.0.1
> * jQuery Plugin for displaying dropdown list of Philippines' Region, Province, City and Barangay in your webpage.
> * https://github.com/buonzz/jquery-ph-locations
> * Made by Buonzz Systems
> * Under MIT License
>   */
> 
> ```
> ;( function( $, window, document, undefined ) {
> 	var filterfieldname = "";
> 	
> 	"use strict";
> 
> 		// defaults
> 		var pluginName = "ph_locations",
> 			defaults = {
>                 location_type : "city", // what data this control supposed to display? regions, provinces, cities or barangays?,
> 				api_base_url: 'https://ph-locations-api.buonzz.com/',
> 				order: "name asc",
> 				filter: {}
>             };
> 
> 		// plugin constructor
> 		function Plugin ( element, options ) {
> 			this.element = element;
> 			this.settings = $.extend( {}, defaults, options );
> 			this._defaults = defaults;
> 			this._name = pluginName;
> 			this.init();
> 		}
> 
> 		// Avoid Plugin.prototype conflicts
> 		$.extend( Plugin.prototype, {
> 			init: function() {
> 				return this
>             },
>             
> 			fetch_list: function (filter) {
> 				
> 				this.settings.filter = filter;
> 					
> 				$.ajax({
>                     type: "GET",
>                     url: this.settings.api_base_url + 'v1/' +  this.settings.location_type,
> 					success: this.onDataArrived.bind(this),
> 					data: $.param(this.map_parameters())
>                 });
> 				
> 
> 				if (this.settings.location_type == "regions") {
> 					filterfieldname="- SELECT REGION -";
> 				} 
> 				else if (this.settings.location_type == "provinces") {
> 					filterfieldname="- SELECT PROVINCE -";
> 				} 
> 				else if (this.settings.location_type == "cities") {
> 					filterfieldname="- SELECT CITY/MUNICIPALITY -";
> 				}
> 				else {
> 					filterfieldname="- SELECT BARANGAY -";
> 				};
> 				
> 
>             }, // fetch list
>             onDataArrived(data){
> 				var shtml = "";
> 				$(this.element).html(this.build_options(data));
> 			},
> 
> 			map_parameters(){
> 
> 				var mapped_parameter = {"filter": {
> 					"where": {},
> 					"order" : this.settings.order
> 					}
> 				};
> 
> 				 for(var property in this.settings.filter)
> 				    mapped_parameter.filter.where[property] = this.settings.filter[property];
> 
> 				 return mapped_parameter;
> 			},
> 
> 			build_options(params){
> 				var shtml = "";
> 				shtml += '<option value="">'+ filterfieldname + '</option>';
> 				for(var i=0; i<params.data.length;i++){
> 					shtml += '<option value="' + params.data[i].id + '">';
> 					shtml +=  params.data[i].name ;
> 					shtml += '</option>';
> 				}
> 
> 				return shtml
> 			}
>             
> 		} );
> 
> 
> 		$.fn[ pluginName ] = function( options, args ) {
> 			return this.each( function() {
> 				var $plugin = $.data( this, "plugin_" + pluginName );
> 				if (!$plugin) {
> 					var pluginOptions = (typeof options === 'object') ? options : {};
> 					$plugin = $.data( this, "plugin_" + pluginName, new Plugin( this, pluginOptions ) );
> 				}
> 				
> 				if (typeof options === 'string') {
> 					if (typeof $plugin[options] === 'function') {
> 						if (typeof args !== 'object') args = [args];
> 						$plugin[options].apply($plugin, args);
> 					}
> 				}
> 			} );
> 		};
> 
> } )( jQuery, window, document );
> 
> 
> 
> **index.php**
> 
> <!DOCTYPE html>
> 
> <html lang="en">
> 	<head>
> 		
> 		<meta charset="utf-8">
> 		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
> 		
> 		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
> 	
> 		
> 	</head>
> 	
> 	<title>Philippine Address</title>
> 	
> 	<body>
> 		<div class="container-fluid" style="margin-top: 10px;">
> 			<div class="col col-4">
> 			<label for = "reg"><b>Region</b></label>
> 			<select class="form-control form-control-sm" id="region" name="region">
> 			</select>	
> 							
> 			<label for = "prov"><b>Province</b></label>
> 			<select class="form-control form-control-sm" id="province" name="province">
> 			</select>	
> 
> 			<label for = "mun"><b>City/Municipality</b></label>
> 			<select class="form-control form-control-sm" id="city" name="city">
> 			</select>		
> 
> 			<label for = "brgy"><b>Barangay</b></label>
> 			<select class="form-control form-control-sm" id="barangay" name="barangay">
> 			</select>
> 			</div>
> 		</div>
> 		
> 		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.js"></script>
> 		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.js"></script>
> 		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
> 		
> 		<script src="jquery.ph-locations.js"></script>
>         <script type="text/javascript">
> 			$(document).ready(function(){
> 				var my_handlers = {
> 					fill_provinces:  function(){
> 						var region_code = $(this).val();	
> 						$('#province').ph_locations('fetch_list', [{"region_code": region_code}]);
> 					},
> 					fill_cities: function(){
> 						var province_code = $(this).val();
> 						$('#city').ph_locations( 'fetch_list', [{"province_code": province_code}]);
> 					},
> 					fill_barangays: function(){
> 						var city_code = $(this).val();
> 						$('#barangay').ph_locations('fetch_list', [{"city_code": city_code}]);
> 					}
> 				};
> 				$('#region').ph_locations({'location_type': 'regions'});
> 				$('#province').ph_locations({'location_type': 'provinces'});
> 				$('#city').ph_locations({'location_type': 'cities'});
> 				$('#barangay').ph_locations({'location_type': 'barangays'});
> 				$('#region').ph_locations('fetch_list');
> 				$('#region').change(my_handlers.fill_provinces);
> 				$('#province').change(my_handlers.fill_cities);
> 				$('#city').change(my_handlers.fill_barangays); 
> 
> 			});
> 		</script>
> 		
> 	</body>
> </html>
> ```

bro how i can fetch the data address and update it.
