### ISSUE TITLE
cost issue

### ISSUE THREAD

**Issue by buonzz** [buonzz/jquery-ph-locations#40]
Hi Guys,

this plugin requires a rest api https://ph-locations-api.buonzz.com/
the cost of running the server is around $20/month. 
I have been trying to keep up the server for the last several years, but after 3 years, its not sustainable anymore.
thus, Im shutting down the server...

what does that mean to you:
- if you are using this plugin, you might need to start considering to self-host the API.
- provision a mysql server that the api can use.

I've open-sourced the api here : https://github.com/buonzz/ph-locations-api
its something that can be deployed in heroku, if you don't have your own server( or ask your client to host it)
see https://docs.adonisjs.com/cookbooks/deploy-to-heroku

you can find the sql dump in here: https://f001.backblazeb2.com/file/buonzz-assets/phlocations.sql
 
apologies for the inconvinience this caused.

thank you all

**Comment by Saiyaneren** [comment]
@buonzz Good Day Sir! We are using your API from our project, and we have a presentation for tomorrow, and we notice that the API is not working anymore. Can we have the code before you push today?

**Comment by twilight04** [comment]
Can I use the source in my localhost?

**Comment by twilight04** [comment]
> > Can I use the source in my localhost?
> 
> yes, you can host it locally. its a standard nodejs application

I've tried to import the sql dump but there's an error. How can I fix that?

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"phlocations" /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_...' at line 1

**Comment by buonzz** [comment]
> > > Can I use the source in my localhost?
> > 
> > 
> > yes, you can host it locally. its a standard nodejs application
> 
> I've tried to import the sql dump but there's an error. How can I fix that?
> 
> #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"phlocations" /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_...' at line 1

maybe try removing the comments, some solution can be found here. https://stackoverflow.com/questions/1916392/how-can-i-get-rid-of-these-comments-in-a-mysql-dump

this sql  dump is from mysql server v8, if that helps

**Comment by twilight04** [comment]
> > > > Can I use the source in my localhost?
> > > 
> > > 
> > > yes, you can host it locally. its a standard nodejs application
> > 
> > 
> > I've tried to import the sql dump but there's an error. How can I fix that?
> > #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"phlocations" /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_...' at line 1
> 
> maybe try removing the comments, some solution can be found here. https://stackoverflow.com/questions/1916392/how-can-i-get-rid-of-these-comments-in-a-mysql-dump
> 
> this sql dump is from mysql server v8, if that helps

I see, I'm currently using the API for my thesis and it suddenly doesn't work. So I really need it, thanks for answering my questions.

**Comment by roidMB** [comment]
https://psgc.gitlab.io/api/

@twilight04 

Hi you can use this instead for your thesis. Cheers.

**Comment by JohnLloyd2335** [comment]
> how can you show me an example?

**Comment by buonzz** [comment]
hi guys, manage to take the api online, BUT with limited capacity. its using heroku free dyno,which resets every month once my free credit ran out...

its good for demo/testing purposes, but not for production use.
so i would encourage you to host it in your own servers for heavy traffic sites
