### ISSUE TITLE
ph-locations-api.buonzz.com/v1/regions:1     Failed to load resource: net::ERR_FAILED

### ISSUE THREAD

**Issue by AppDeepCorp** [buonzz/jquery-ph-locations#53]
ph-locations-api.buonzz.com/v1/regions:1     Failed to load resource: net::ERR_FAILED

**Comment by buonzz** [comment]
this is due to cost of maintaining the service issue. kindly check https://github.com/buonzz/jquery-ph-locations/issues/59
