### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by arshleytan** [buonzz/jquery-ph-locations#54]
API not working, I am getting this error: Access to XMLHttpRequest at 'https://ph-locations-api.buonzz.com/v1/regions?filter%5Border%5D=name%20asc' from origin 'https://www.darwinbiler.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by buonzz** [comment]
this is due to cost of maintaining the service issue. kindly check https://github.com/buonzz/jquery-ph-locations/issues/59
