### ISSUE TITLE
please fix the error Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by notna94** [buonzz/jquery-ph-locations#58]
i want your ph api location for my project but here is i encountered errors:

Error: getaddrinfo ENOTFOUND myboarders-db1.cz5rvnohbzyu.us-east-1.rds.amazonaws.com myboarders-db1.cz5rvnohbzyu.us-east-1.rds.amazonaws.com:3306

Thank you!

**Comment by Scraper001** [comment]
I also have this error :(

Error: getaddrinfo ENOTFOUND myboarders-db1.cz5rvnohbzyu.us-east-1.rds.amazonaws.com myboarders-db1.cz5rvnohbzyu.us-east-1.rds.amazonaws.com:3306

**Comment by buonzz** [comment]
this is due to cost of maintaining the service issue. kindly check https://github.com/buonzz/jquery-ph-locations/issues/59
